# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-app-v1
#   labels:
#     app: my-app
#     version: v1
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: my-app
#       version: v1
#   template:
#     metadata:
#       labels:
#         app: my-app
#         version: v1
#     spec:
#       containers:
#       - name: my-app
#         image: my-app:v1
#         ports:
#         - containerPort: 80




# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-app-v2
#   labels:
#     app: my-app
#     version: v2
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: my-app
#       version: v2
#   template:
#     metadata:
#       labels:
#         app: my-app
#         version: v2
#     spec:
#       containers:
#       - name: my-app
#         image: my-app:v2
#         ports:
#         - containerPort: 80



# apiVersion: v1
# kind: Service
# metadata:
#   name: my-app-service
# spec:
#   selector:
#     app: my-app
#     version: v1
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   type: ClusterIP




# kubectl patch service my-app-service -p '{"spec":{"selector":{"version":"v2"}}}'




# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-app-stable
#   labels:
#     app: my-app
#     version: stable
# spec:
#   replicas: 5
#   selector:
#     matchLabels:
#       app: my-app
#       version: stable
#   template:
#     metadata:
#       labels:
#         app: my-app
#         version: stable
#     spec:
#       containers:
#       - name: my-app
#         image: my-app:stable
#         ports:
#         - containerPort: 80



# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-app-canary
#   labels:
#     app: my-app
#     version: canary
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: my-app
#       version: canary
#   template:
#     metadata:
#       labels:
#         app: my-app
#         version: canary
#     spec:
#       containers:
#       - name: my-app
#         image: my-app:canary
#         ports:
#         - containerPort: 80




apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "16"
spec:
  rules:
  - host: my-app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-app-service
            port:
              number: 80
