# Utiliser des sélecteurs complexes pour gérer des groupes de pods.
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  labels:
    app: web
    env: dev
spec:
  containers:
  - name: nginx-container-for-simple-web-pod
    image: nginx:latest
    ports:
    - containerPort: 80



---
apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  labels:
    app: web
    env: production
spec:
  containers:
  - name: nginx-container-for-simple-web-pod
    image: nginx:latest
    ports:
    - containerPort: 80



---
apiVersion: v1
kind: Pod
metadata:
  name: pod-c
  labels:
    app: api
    env: dev
spec:
  containers:
  - name: nginx-container-for-simple-web-pod
    image: nginx:latest
    ports:
    - containerPort: 80



---
apiVersion: v1
kind: Pod
metadata:
  name: pod-d
  labels:
    app: api
    env: production
spec:
  containers:
  - name: nginx-container-for-simple-web-pod
    image: nginx:latest
    ports:
    - containerPort: 80



